### ISSUE TITLE
Unknown ICAP Mode "FILEMOD" -> Exception

### ISSUE THREAD

**Issue by tombueng** [toolarium/toolarium-icap-client#3]
When die ICAPMode "FILEMOD" (Unknown to this ICAP-client) is sent. The client will throw an Exception:

java.lang.IllegalArgumentException: No enum constant com.github.toolarium.icap.client.dto.ICAPMode.FILEMOD
at java.lang.Enum.valueOf(Enum.java:238)
at com.github.toolarium.icap.client.dto.ICAPMode.valueOf(ICAPMode.java:14)
at com.github.toolarium.icap.client.impl.ICAPClientImpl.options(ICAPClientImpl.java:131)
at com.github.toolarium.icap.client.impl.ICAPClientImpl.options(ICAPClientImpl.java:77)
at com.github.toolarium.icap.client.ICAPClientFactory.getICAPClient(ICAPClientFactory.java:193)
at com.github.toolarium.icap.client.ICAPClientFactory.getICAPClient(ICAPClientFactory.java:110)

Unknown mode shall not crash the client but be ignored.

Example Server that supports FILEMOD: https://techdocs.broadcom.com/content/dam/broadcom/techdocs/symantec-security-software/information-security/symantec-protection-engine/generated-pdfs/SPE_NAS_SDK_Guide.pdf

**Comment by mepux** [comment]
Best thanks!

**Comment by mepux** [comment]
Resolved in release v1.2.0
