### ISSUE TITLE
REQMOD support

### ISSUE THREAD

**Issue by anilbptl** [toolarium/toolarium-icap-client#6]
The symantec server supports REQMOD only. The options response is as follows. 

ICAP/1.0 200 OK
ISTag: "Vontu12.0"
Methods: REQMOD
Options-TTL: 3600
Preview: 4096
Transfer-Preview: *
Allow: 204
X-Include: X-Client-IP, X-Authenticated-User
Encapsulated: null-body=0
Max-Connections: 16

Even then the scan request is sent as RESMOD which is resulting into failure of the scan.

**Comment by mepux** [comment]
Thanks for your feedback, which I can not follow an issue. You should simply choose the supported mode in the case above the REQMOD. This should work properly; otherwise, please describe the issue with more detailed.

**Comment by anilbptl** [comment]
Thank you for the response. I have tried by using REQMOD. The following is the test code which I have used. 


  ```

          try {
                try {
                 ICAPClient icapClient = ICAPClientFactory.getInstance().getICAPClient(hostName, 1344, "REQMOD");
                    ICAPHeaderInformation icapHeaderInformation = icapClient.validateResource(ICAPMode.REQMOD,
                            new ICAPRequestInformation("Anil"
                                    , "file"),
                            new ICAPResource(file.getName(), new FileInputStream(file), file.length()));
                    System.out.println(icapHeaderInformation);
                } catch (ContentBlockedException e) {
                    System.out.println(e.getICAPHeaderInformation());
                    if (e.getContent() != null) {
                        System.out.println("---> Response content: \n" + e.getContent());
                    }
                    e.printStackTrace();

                }
            } catch (IOException e) {
                e.printStackTrace();
            }

```

The following are the debug logs.
```

12:10:56.248 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 6D606A66 - Send create socket to [172.16.18.137:1344/REQMOD]
12:10:56.347 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 6D606A66 - Send request:
OPTIONS icap://172.16.18.137/REQMOD ICAP/1.0
Host: 172.16.18.137
User-Agent: toolarium ICAP-Client/1.1
Encapsulated: null-body=0


12:10:56.348 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 6D606A66 - Flushed request of [172.16.18.137:1344/REQMOD]
12:10:56.415 [main] DEBUG com.github.toolarium.icap.client.impl.ChunkedInputStream - 6D606A66 - HTTP headers:
ICAP/1.0 200 OK
ISTag: "Vontu12.0"
Methods: REQMOD
Options-TTL: 3600
Preview: 4096
Transfer-Preview: *
Allow: 204
X-Include: X-Client-IP, X-Authenticated-User
Encapsulated: null-body=0
Max-Connections: 16

12:11:02.171 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 6D606A66 - Received ICAP response status: ICAP/1.0 200 OK
12:11:02.174 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPClientImpl - 6D606A66 - Server preview size: 4096
12:11:02.183 [main] INFO com.github.toolarium.icap.client.impl.ICAPClientImpl - 6D606A66 - Valid service [200/OK], allow 204: true, available methods: [REQMOD]
12:11:02.184 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 6D606A66 - Close socket of [172.16.18.137:1344/REQMOD]
12:11:02.195 [main] DEBUG com.github.toolarium.icap.client.ICAPClientFactory - Set remote service configuration cache: ICAPServiceInformation [hostName=172.16.18.137, servicePort=1344, secureConnection=false, serviceName=REQMOD, cacheMaxAgeInSeconds=43200]
12:11:23.285 [main] INFO com.github.toolarium.icap.client.impl.ICAPClientImpl - 871B6577 - Validate resource (username: Anil, source: file, resource: SSN_Docx_1999.docx, length: 22349)
12:11:27.044 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 871B6577 - Send create socket to [172.16.18.137:1344/REQMOD]
12:11:31.226 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPClientImpl - 871B6577 - Use allow 204: auto select (suppported by the icap-server)
12:11:31.237 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 871B6577 - Send request:
RESPMOD icap://172.16.18.137/REQMOD ICAP/1.0
Host: 172.16.18.137
Connection:  close
User-Agent: toolarium ICAP-Client/1.1
Allow: 204
Preview: 4096
Encapsulated: req-hdr=0, res-hdr=62, res-body=132

GET /SSN_Docx_1999.docx HTTP/1.1
Host: 172.16.18.137:1344

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Length: 22349

1000

12:11:31.240 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 871B6577 - Flushed request of [172.16.18.137:1344/REQMOD]
12:11:31.338 [main] DEBUG com.github.toolarium.icap.client.impl.ChunkedInputStream - 871B6577 - HTTP headers:
ICAP/1.0 405 Method not allowed for service
Connection: close

12:11:31.338 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 871B6577 - Received ICAP response status: ICAP/1.0 405 Method not allowed for service
12:11:31.340 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 871B6577 - Close socket of [172.16.18.137:1344/REQMOD]
12:11:31.342 [main] WARN com.github.toolarium.icap.client.impl.ICAPClientImpl - 871B6577 - Could not access to ICAP server: Server returned unknown status code:405
```

The method com.github.toolarium.icap.client.impl.ICAPClientImpl#processResource is hard coded to send as RESPMOD.
```

 String requestBuffer = "RESPMOD icap://" + serviceInformation.getHostName() + "/" + serviceInformation.getServiceName() + " ICAP/" + requestInformation.getApiVersion() + NEWLINE
                        + "Host: " + serviceInformation.getHostName() + NEWLINE
                        + "Connection:  close" + NEWLINE 
                        + "User-Agent: " + requestInformation.getUserAgent() + NEWLINE 
                        + supportAllow204(requestIdentifier, requestInformation.isAllow204())
                        + "Preview: " + previewSize + NEWLINE 
                        + "Encapsulated: req-hdr=0, res-hdr=" + resHeader.length() + ", res-body=" + resBody.length() + NEWLINE + NEWLINE 
                        + resBody
                        + Integer.toHexString(previewSize) + NEWLINE;
```

Please let me know If I miss anything.

**Comment by mepux** [comment]
Thanks, yes there is an issue which will be fixed.

**Comment by anilbptl** [comment]
Could you share the timelines for the fix?

**Comment by mepux** [comment]
It's released in v1.2.0

**Comment by anilbptl** [comment]
Hi, Seems to be there is some issue existed while sending the content. 
The wireshark shows that the tcp packet is malformed. 

![image](https://user-images.githubusercontent.com/11077149/201589308-a0cd0938-b53c-49f5-8538-aa58b1937869.png)

I have used https://github.com/jmimo/netty-icap this tool(which has outdated netty library) to test the sample violated file. When I used netty-icap library it is tagged violated but when I use this library the server is not able to detect the violation. It is returning 204 response.

**Comment by mepux** [comment]
The communication follows the ICAP spec https://www.rfc-editor.org/rfc/rfc3507.html. The content is sent proper to the back end. It's tested by positive and negative cases (eicar test virus). The library just sends the content and the backend is responsible to detect a violation. The library sends back transparent the detected violations if any.

**Comment by anilbptl** [comment]
I have tried with another DLP server. Here I got a exception in the logs.
```

12:41:03.612 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 9ACA354B - Send create socket to [51.79.47.111:1344/REQMOD]
12:41:03.953 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 9ACA354B - Send request:
OPTIONS icap://51.79.47.111:1344/REQMOD ICAP/1.0
Host: 51.79.47.111
User-Agent: toolarium ICAP-Client/1.1
Encapsulated: null-body=0


12:41:03.953 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 9ACA354B - Flushed request of [51.79.47.111:1344/REQMOD]
12:41:04.267 [main] DEBUG com.github.toolarium.icap.client.impl.ChunkedInputStream - 9ACA354B - HTTP headers:
ICAP/1.0 200 OK
Server: Traffic Spicer 2.2.2
ISTag: "PA/v2.2.2/c6fef14/v3.2.2"
Methods: REQMOD
Allow: 204
Preview: 0
Transfer-Preview: *
Max-Connections: 10
X-Include: X-Client-IP, X-Server-IP, X-Authenticated-User, X-Authenticated-Groups
X-PanaAdapter-Huge-Content-Size: 50485760

12:41:04.268 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 9ACA354B - Response header: {X-ICAP-Statusline=[ICAP/1.0 200 OK], Server=[Traffic Spicer 2.2.2], ISTag=["PA/v2.2.2/c6fef14/v3.2.2"], Methods=[REQMOD], Allow=[204], Preview=[0], Transfer-Preview=[*], Max-Connections=[10], X-Include=[X-Client-IP, X-Server-IP, X-Authenticated-User, X-Authenticated-Groups], X-PanaAdapter-Huge-Content-Size=[50485760]}
12:41:04.269 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 9ACA354B - Received ICAP response status: ICAP/1.0 200 OK
12:41:04.274 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPClientImpl - 9ACA354B - Server preview size: 0
12:41:04.284 [main] INFO com.github.toolarium.icap.client.impl.ICAPClientImpl - 9ACA354B - Valid service [200/OK], allow 204: true, available methods: [REQMOD]
12:41:04.285 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - 9ACA354B - Close socket of [51.79.47.111:1344/REQMOD]
12:41:04.301 [main] DEBUG com.github.toolarium.icap.client.ICAPClientFactory - Set remote service configuration cache: ICAPServiceInformation [hostName=51.79.47.111, servicePort=1344, secureConnection=false, serviceName=REQMOD, cacheMaxAgeInSeconds=43200]
12:41:04.304 [main] INFO com.github.toolarium.icap.client.impl.ICAPClientImpl - BEA6BD0 - Validate resource (username: Anil, source: file, resource: SSN_Docx_2000.docx, length: 46608)
12:41:04.993 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - BEA6BD0 - Send create socket to [51.79.47.111:1344/REQMOD]
12:41:05.348 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPClientImpl - BEA6BD0 - Use allow 204: auto select (suppported by the icap-server)
12:41:05.394 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - BEA6BD0 - Send request:
REQMOD icap://51.79.47.111:1344/REQMOD ICAP/1.0
Host: 51.79.47.111
Connection:  close
User-Agent: toolarium ICAP-Client/1.1
Allow: 204
Preview: 0
Encapsulated: req-hdr=0, req-body=131

GET /SSN_Docx_2000.docx HTTP/1.1
Host: 51.79.47.111:1344

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Length: 46608

0

12:41:05.691 [main] DEBUG com.github.toolarium.icap.client.impl.ChunkedInputStream - BEA6BD0 - HTTP headers:

12:41:05.692 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - BEA6BD0 - Response header: {}
12:41:05.698 [main] DEBUG com.github.toolarium.icap.client.impl.ICAPSocket - BEA6BD0 - Close socket of [51.79.47.111:1344/REQMOD]
12:41:05.698 [main] WARN com.github.toolarium.icap.client.impl.ICAPClientImpl - BEA6BD0 - Could not access to ICAP server: Server returned unknown status code:0
java.io.IOException: Server returned unknown status code:0
	at com.github.toolarium.icap.client.impl.ICAPClientImpl.processResource(ICAPClientImpl.java:334)
	at com.github.toolarium.icap.client.impl.ICAPClientImpl.validateResource(ICAPClientImpl.java:189)
	at com.lkt.Test.main(Test.java:31)

```
